# -*- coding: utf-8 -*-
"""Mathplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Bwdz1C0sLqmOSNIjwRiRext6G9VWCMu
"""

import matplotlib.pyplot as plt

x_values = range(1, 1001)
y_values = [x**2 for x in x_values]
plt.style.use('seaborn-v0_8')
fig, ax = plt.subplots()
ax.scatter(x_values, y_values, c=y_values, cmap=plt.cm.Blues,  s=10)
#ax.plot(input_values, squares, linewidth=3)

ax.set_title("Square Numbers", fontsize=24)
ax.set_xlabel("Value", fontsize=14)
ax.set_ylabel("Square of Value", fontsize=24)
ax.tick_params(labelsize=24)
ax.axis([0, 1100, 0, 1100000])
ax.ticklabel_format(style='plain')
plt.show()